### ISSUE TITLE
Panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by omeid** [tdewolff/parse#15]
```go

package main

import (
	"bytes"
	"fmt"
	"io/ioutil"
	"log"

	"github.com/tdewolff/buffer"
	"github.com/tdewolff/minify"
	"github.com/tdewolff/minify/css"
	"github.com/tdewolff/minify/html"
	"github.com/tdewolff/minify/js"
	"github.com/tdewolff/minify/svg"
)

func main() {
	buff := new(bytes.Buffer)
	file := buffer.NewReader([]byte(`<!DOCTYPE html>
<html lang='en' ng-app="app" ng-cloak="ng-cloak">
    <head>
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1.0, minimum-sacle=1.0, maximum-scale=1.0, user-scalable=no'>
        <meta name='description' content=''>
        <base href='/'>
        <title>Golang Angular Materail Todo App </title>
        <link rel='shortcut icon' href='/favicon.ico'>
        <link rel='stylesheet' href='/assets/style.min.css'>
        <script src="/assets/libs.min.js">
        </script>
        <script src="/assets/app.min.js">
    
        </script>
    </head>
    <body ng-controller="todos" layout="column">
        <script id="new_list" type="text/ng-template">
            <md-dialog aria-label='Add Todo List' ng-cloak="ng-cloak" flex="70">
                <form name='form' ng-submit="add_list(newlist)" novalidate="novalidate">
                    <md-toolbar>
                        <div class="md-toolbar-tools">
                            <h2>Add Todo List</h2><span flex="flex">                            </span>
                            <md-button class="md-icon-button" ng-click='cancel()'>
                                <md-icon>cancel</md-icon>
                            </md-button>
                        </div>
                    </md-toolbar>
                    <md-dialog-content flex="flex">
                        <div class="md-dialog-content">
                            <md-input-container class="md-block">
                                <input ng-model='list.Name' type="text" name="Name" placeholder='Name' required="required">
                                <div ng-messages="form.Name.$error" ng-if="form.Name.$invalid && form.Name.$touched">
                                    <p ng-message="required">Name is required.</p>
                                </div>
                            </md-input-container>
                            <md-input-container class="md-block">
                                <input ng-model='list.Color' type="color" name="Color" placeholder='Color' required="required">
                                <div ng-messages="form.Color.$error" ng-if="form.Color.$invalid && form.Color.$touched">
                                    <p ng-message="required">Color is required.</p>
                                </div>
                            </md-input-container>
                        </div>
                    </md-dialog-content>
                    <md-dialog-actions layout='row'><span flex=''>                        </span>
                    </md-dialog-actions>
                </form>
            </md-dialog>
        </script>
        <script id="new_todo" type="text/ng-template">
            <md-dialog aria-label='Add Todo List' ng-cloak="ng-cloak" flex="70">
                <form name='form' ng-submit="add_list(newlist)" novalidate="novalidate">
                    <md-toolbar>
                        <div class="md-toolbar-tools">
                            <h2>Add Todo Item</h2><span flex="flex">                            </span>
                            <md-button class="md-icon-button" ng-click='cancel()'>
                                <md-icon>cancel</md-icon>
                            </md-button>
                        </div>
                    </md-toolbar>
                    <md-dialog-content flex="flex">
                        <div class="md-dialog-content">
                            <md-input-container class="md-block">
                                <input ng-model='newlist' name="Name" placeholder='Name' required="required">
                                <div ng-messages="form.Name.$error" ng-if="form.Name.$invalid && form.Name.$touched">
                                    <p ng-message="required">Name is required.</p>
                                </div>
                            </md-input-container>
                        </div>
                    </md-dialog-content>
                    <md-dialog-actions layout='row'><span flex=''>                        </span>
                        <md-button class="md-primary" type="submit">Add List

      
                        </md-button>
                    </md-dialog-actions>
                </form>
            </md-dialog>
        </script>
        <md-toolbar>
            <div class="md-toolbar-tools">
                <h3>My Todo Lists</h3><span flex="flex">                </span>
                <md-button class="md-icon-button" aria-label='Add' ng-click='new_list($event)'>
                    <md-icon>add</md-icon>
                </md-button>
            </div>
        </md-toolbar>
        <md-content layout="row" flex="flex">
            <div class="md-padding list" layout="row" flex="flex" ng-repeat="(name, list) in todos">
                <div class="md-whiteframe-1dp" layout="column" flex="flex">
                    <md-toolbar flex="flex">
                        <div class="md-toolbar-tools">
                            <h3>{{name}}</h3><span flex="flex">                            </span>
                            <md-button class="md-icon-button">
                                <md-icon>add</md-icon>
                            </md-button>
                        </div>
                    </md-toolbar>
                    <md-content layout="column">
                        <md-list>
                            <md-list-item ng-repeat='todo in list'>
                                <md-checkbox></md-checkbox>
                                <p> {{ todo.Content }} </p>
                            </md-list-item>
                        </md-list>
                    </md-content>
                </div>
            </div>
        </md-content>
        <!-- At the end because we need the dom. -->
   
    </body>
</html>`))

	m := minify.New()
	m.Add("text/html", &html.Minifier{
		KeepDefaultAttrVals: true,
		KeepWhitespace:      true,
	})
	m.AddFunc("text/css", css.Minify)
	m.AddFunc("text/javascript", js.Minify)
	m.AddFunc("image/svg+xml", svg.Minify)

	err := m.Minify("text/html", buff, ioutil.NopCloser(file))
	if err != nil {
		log.Fatal(err)
	}

	fmt.Printf("buff: %s", buff.Bytes())
}
```

Panics with the follow trace:
```
2016/01/10 19:11:19 RAWTAG text/ng-template
2016/01/10 19:11:19 RAWTAG  list'>
        
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/tdewolff/parse.Mediatype(0xc8200acaa7, 0xf, 0x559, 0x0, 0x0, 0x0, 0x0)
	/home/ome/go/src/github.com/tdewolff/parse/common.go:222 +0x4bf
github.com/tdewolff/minify/html.(*Minifier).Minify(0xc82000aca0, 0xc8200125d0, 0x7ff5356e22b8, 0xc82001a2a0, 0x7ff5356e22e0, 0xc82000acb0, 0x0, 0x0, 0x0)
	/home/ome/go/src/github.com/tdewolff/minify/html/html.go:105 +0x4d26
github.com/tdewolff/minify.(*M).MinifyMimetype(0xc8200125d0, 0xc82000acc0, 0x9, 0x10, 0x7ff5356e22b8, 0xc82001a2a0, 0x7ff5356e22e0, 0xc82000acb0, 0x0, 0x0, ...)
	/home/ome/go/src/github.com/tdewolff/minify/minify.go:116 +0x13e
github.com/tdewolff/minify.(*M).Minify(0xc8200125d0, 0x59bdc0, 0x9, 0x7ff5356e22b8, 0xc82001a2a0, 0x7ff5356e22e0, 0xc82000acb0, 0x0, 0x0)
	/home/ome/go/src/github.com/tdewolff/minify/minify.go:107 +0xec
main.main()
	/home/ome/go/src/test/test.go:142 +0x669
```

**Comment by tdewolff** [comment]
I can't seem to reproduce the out-of-bounds. I assume you run the latest (master) version, right?

The only mediatype is 'text/ng-template' which is parsed fine. What spits out the first two lines of your trace output?

**Comment by omeid** [comment]
The first two lines comes from a print statement which I added trying to understand what is going on:

```go
minify/html/html.go
104:	 log.Printf("RAWTAG %s", rawTagMediatype)
```

Packages that I am using:


tdewollf/buffer@43cef5b - 10 weeks ago : Add MinBuf for old parse versions
tdewollf/minify@e15ad1a - 7 weeks ago : golint
tdewollf/parse@c7631ca - 7 weeks ago : golint

**Comment by omeid** [comment]
Same issue with latest versions.

tdewollf/buffer@43cef5b - 10 weeks ago : Add MinBuf for old parse versions
tdewollf/minify@c7ed5d3 - 4 weeks ago : Readme update; remove comparison
tdewollf/parse@926cfdd - 4 weeks ago : Make keeping newlines the default

using
```sh
go1.5.1 linux/amd64
Linux 4.2.8-200.fc22.x86_64 x86_64 x86_64
```

**Comment by tdewolff** [comment]
This is weird. I can only reproduce this on a Linux but not on a Windows machine! It appeared to be using memory that was already freed for the mediatype.

Let me know if you still encounter problems.

**Comment by omeid** [comment]
All seems good. Thanks a lot for the quick fix!
